### ISSUE TITLE
The output parameter installed power capacity must be redefined

### ISSUE THREAD

**Issue by FredericHirschmueller** [rl-institut/open_plan#101] opened 2020-12-09 13:51 UTC
We have to make two different outputs with two different units:
installed power [kW]
installed capacity [kWh]

**Comment by TheOneAndra** [comment] 2020-12-10 14:30
PR #100 has been updated accordingly, thank you for the comment

**Comment by Bachibouzouk** [comment] 2021-01-04 15:47
#100 is not merged yet, therefore the issue is not closed ;)

The way to go is to write `fix #101` in the description of #100, so when it gets merged, it closes this issue automatically :D

**Comment by TheOneAndra** [comment] 2021-01-05 08:05
> The way to go is to write `fix #101` in the description of #100, so when it gets merged, it closes this issue automatically :D

Actually this is not necessary since the PR has been linked from here already:
![grafik](https://user-images.githubusercontent.com/66671861/103621303-4a19d500-4f35-11eb-9bd8-854af5feb31e.png)


Nevertheless, does that make it easier to read when someone in a distance future searches for this? Because technically, this issue has been adressed so it could be closed

**Comment by Bachibouzouk** [comment] 2021-01-05 09:20
Technically the issue has been addressed when the branch is merged in `dev`, this is not the case yet. (things could go banana and #100 end up deleted and not merged, then we did not solve the issue but think we did because we closed it already)

I did not know the button to link the issue, I think I still prefer explicitly writing Fix #issuenumber as per the "explicit over implicit" principle.

**Closed as completed** 2021-03-09 09:32 UTC
